services:
  backend:
    image: bombparty-backend   # İnternetten değil, az önce bizim yarattığımız imaj
    container_name: bombparty-backend
    restart: always
    environment:
      - PORT=3001
      - CORS_ORIGIN=https://oyun.anilaltan.com
    ports:
      - "3001:3001"

  frontend:
    image: bombparty-frontend  # Bizim yarattığımız frontend imajı
    container_name: bombparty-frontend
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - backend